sonar.projectKey=advprog-2026-A17-project_bidmart-infrastructure
sonar.organization=advprog-2026-a17-project
sonar.projectName=bidmart-infrastructure
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

sonar.exclusions=\
  .github/workflows/**,\
  deploy/**,\
  monitoring/**,\
  scripts/**,\
  **/*.yml,\
  **/*.yaml,\
  **/*.sh

sonar.coverage.exclusions=\
  src/main/java/**/config/**,\
  src/main/java/**/security/**

sonar.newCode.referenceBranch=main
